################################################################################
# Example Web application with phpmyadmin
# running Apache 2, php 7.1 FPM and mariadb all linked together anbd ready 2 use
################################################################################
version: '2'
services:
  php:
    # change to :5.6-fpm or :7.1-fpm tag to run another php version
    image: ctsmedia/php:7.1-fpm
    ports:
      - "9000"
    volumes:
      - ".:/var/www/share/project"

  db:
    # you can also use mysql:5.6 for example
    image: mariadb:10.1
    environment:
      # change the mysql root password
      MYSQL_ROOT_PASSWORD: ctsmedia
      # change the myprojectname to your likings or set custom values each
      MYSQL_DATABASE: &project myprojectname
      MYSQL_USER: *project
      MYSQL_PASSWORD: *project

  http:
    image: ctsmedia/apache:2.4
    environment:
      # if the pub dir ist not the src root define the relative path here
      PHPFPM_PUBLIC_FOLDER:
      # Set php fpm setting if not standard
      # PHPFPM_HOST: php
      # PHPFPM_PATH: /var/www/share/project/
    volumes_from:
      - php
    depends_on:
#      - db
      - php
    ports:
        - "80:80"
        - "443:443"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      ports:
       - "8080:80"
